version = "1.2.3"
builder = "spa"

[template_settings]
custom-color = "#f3a833"
background-color = "#121414"
accent-color = "#2D4566"
autoreload = "1"
text-color = "#c7cfcc"
highlight-color = "#73bed3"
