version = "1.1.5"
builder = "spa"

[template_settings]
custom-color = "#f3a833"
highlight-color = "#73bed3"
accent-color = "#2D4566"
autoreload = "1"
background-color = "#121414"
text-color = "#c7cfcc"
